version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-keep-it-secret
    networks:
      - app-network
    volumes:
      - ./backend/users.json:/app/users.json

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
